[package]
name = "dowork"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror="1.0.30"
rayon = "1.5.1"

[dev-dependencies]
rand = "0.8.5"